### ISSUE TITLE
Implement the relaxation rates (collision frequencies) in the NRL formulary

### ISSUE THREAD

**Issue by pheuer** [PlasmaPy/hack-week#23]
The [NRL formulary](https://library.psfc.mit.edu/catalog/online_pubs/NRL_FORMULARY_13.pdf) includes relaxation rates/collision frequencies (pg. 31 in this version) for several collision processes. These are expressed as functions of an integral Phi, which itself is a function of the ratio between the bulk flow energy (1/2 mv^2) and the thermal energy (kT) of the plasma: x. 

The next page (pg. 32) expresses these four frequencies for different combinations of ions and electrons in both the fast (x>>1) and slow (x<<1) limits (in which the integral of x is approximately constant). However, numerically it is easy enough to just evaluate the integral Phi and get one expression for both regimes. 

It would be great to have the integral Phi and the four expressions for the relaxation rates $\nu$ in the PlasmaPy collisions package! In the fast beam limit these are particularly useful for estimating collisionality in shock experiments.

![image](https://user-images.githubusercontent.com/32618747/176002982-4aaa809e-6607-4189-8e88-c41247a1a70a.png)

**Comment by JaydenR2305** [comment]
Hi Peter. I'll give this a try
